jwt:
  access:
    claim-key: logined
    expires-at: 7200
    token-type: Bearer
  refresh:
    claim-key: refresh
    expires-at: 2592000
    token-type: Basic
  authorization-header: Authorization
password:
  encode:
    algorithm: PBKDF2WithHmacSHA1
    iterations: ${AUTH_ITERATIONS}
    keyLength: ${KEY_LENGTH}