spring:
  profiles:
    active: local
    group:
      local: [ local ]
      test: [ test ]
      prod: [ prod ]
    include: [ jwt ]
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
    open-in-view: false
