name: Deploy to Amazon EC2

on:
  push:
    branches: [ "deploy-test" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: prod

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - run: |
        touch ./
        echo "${{secrets.ENV}}" > ./.env
        echo "${{secrets.APPLICATION_PROD}}" > ./config/application-prod.yml

    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew clean build

    - name: docker build and push
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build --platform amd64 --build-arg DEPENDENCY=build/dependency -f ./Dockerfile -t ${{secrets.DOCKER_USERNAME}}/project .
        docker push ${{ secrets.DOCKER_USERNAME }}/project
        
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ubuntu
        key: ${{ secrets.AWS_KEY }}
        script: |
          sudo docker rm -f $(docker ps -qa)
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/project
          sudo docker compose up -d
          sudo docker image prune -a -f
